export default {
  level: ["Beginner", "Intermediate", "Expert"],
  tech: [
    "Anchor",
    "Arweave",
    "Metaplex",
    "Web3.js",
    "Serum",
    "Gaming",
    "Governance",
    "Mobile",
    "Security",
  ],
  language: [
    "Rust",
    "JavaScript",
    "C#",
    "Golang",
    "Python",
    "Java",
    "Swift",
    "CLI",
    "Kotlin",
  ],
  badge: ["New", "Hot", "Best", "Old"],
};
